"""add new relationship many-to-many

Revision ID: 63187e88373e
Revises: 0c4702b40073
Create Date: 2021-02-19 01:04:39.609927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63187e88373e'
down_revision = '0c4702b40073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies_actors',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'film_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies_actors')
    # ### end Alembic commands ###
